### ISSUE TITLE
Getting started with DataView

### ISSUE THREAD

**Issue by rodneytamblyn** [trevordevore/levurehelper-dataview#15]
Hi Trevor,

I have tried to create my first DataView, following instructions in Readme.

- added DataView to my Levure app and configured app.yaml
- from message box called dvIdeCreateDataViewControlUsingDialog
- in dialog selected options:
- name: day_contact_urls
- Checkbox:  Create Row Template >><YES:  I left the field blank (does this default to the "row" template (from the readme: "It is assumed that in the dialog you opted to create a row behavior." - what other options are available?  Would it make sense to list these in a dropdown in the dialog stack?)
- Checkbox: create behaviour for developer >> Yes
- the DataView is created (empty/blank) and I can see scripts template stack created correctly in my project and stackfiles etc set
- attempt to actually SHOW some content in this DataView.  Per instructions in the readme I did following
- Create a button and execute:
``
on mouseUp
   local tA
   put "Line 1" into tA[1]["label"]
   put "Line 2" into tA[2]["label"]
   put "Line 3" into tA[3]["label"]
   put "Line 4" into tA[4]["label"]
   
   set the dvData of group "day_contact_urls" to tA
end mouseUp
``
I then assigned the template to the DV.  Create button and execute:

``
on mouseUp
   local tTemplateStack
   put levureAppFolder() &"/templates/day_contact_urls/day_contact_urls_row_templates.livecode" into tTemplateStack
   if not there is a file tTemplateStack then breakpoint
   put the long id of group "default Row Template" of stack tTemplateStack \
         into tStyleTemplatesA["default"]
   set the viewProp["row style templates"] of group "day_contact_urls" to tStyleTemplatesA
end mouseUp
``

- nothing appears in my DataView.  I think I am missing something here!

Thanks for your help Trevor.

~ Rodney

**Comment by rodneytamblyn** [comment]
Some more information.  The group custom properties
![image](https://user-images.githubusercontent.com/1562956/100832011-d31f9580-34cb-11eb-88cc-4523de0d39ff.png)
- behaviour script set:
![image](https://user-images.githubusercontent.com/1562956/100832024-dd419400-34cb-11eb-9060-692563f235ec.png)
- the stacksinuse:
``
Logger Library
Window Manager Library
Broadcaster Library
Preferences Library
File System Library
DataView Tree IDE Helper Library
DataView IDE Helper Library
levureAppExternals
app
``

**Comment by rodneytamblyn** [comment]
Resolved....

**Comment by trevordevore** [comment]
@rodneytamblyn What was the problem?

**Comment by rodneytamblyn** [comment]
From your tutorial video I discovered it’s critical to pass in the type of array controller when invoking dvIdeCreateDataViewControlUsingDialog
==>  If working through the examples in readme you definitely will want the array controller:

 dvIdeCreateDataViewControlUsingDialog empty, the long id of stack "DataView Array Controller Behavior”

I just called the dialog using dvIdeCreateDataViewControlUsingDialog without (optional, but in this context required) params. I have proposed a slight change to readme to emphasise this.

I think it would be helpful to add a dropdown menu of available (default) controller behaviours in the dialog  

~ Rodney
