### ISSUE TITLE
customising template groups

### ISSUE THREAD

**Issue by rodneytamblyn** [trevordevore/levurehelper-dataview#16]
Hi Trevor,

I worked through the example from your tutorial video.  After creating a divider element I thought perhaps it might make sense for the divider row not to be as high as the other rows in the group.  I tried changing the rect of the template group but this did not result in row changing height in dv.  Is this possible and if so, how?

![image](https://user-images.githubusercontent.com/1562956/100955602-afb42380-357b-11eb-93db-5f8ca3ff4752.png)

~ Rodney

**Comment by trevordevore** [comment]
@rodneytamblyn Is the `viewProp["fixed row height"]` property `true` or `false`? If it is `true` then you can't change the size. If it is `false` then the DataView will size the row based on the height of the template group.

**Comment by rodneytamblyn** [comment]
Brilliant - that will undoubtably be it...

--
Rodney Tamblyn
Co- Founder & CEO | OceanBrowser Ltd
+64 34742102 |  @ocnb3
https://nz.linkedin.com/in/rodneytamblyn

Beautiful study for lifelong learning
http://www.ob3.io

**Comment by rodneytamblyn** [comment]
OK interesting.  Here's my divider row template:
![image](https://user-images.githubusercontent.com/1562956/100963187-b72ef900-358a-11eb-8d79-08e64cdfa866.png)

... but when I apply to my dv with fixed row height set to false it actually increases the row height
![image](https://user-images.githubusercontent.com/1562956/100963031-73d48a80-358a-11eb-8cd7-083b784215f8.png)

**Comment by trevordevore** [comment]
Is there a background graphic in that group as well? If so, is it the same height as the row with the divider template in the screenshot? If it is, just resize the background graphic as well.
