### ISSUE TITLE
selectedRowChanged doesn't fire if set hilight with dvHilitedRows

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levurehelper-dataview#6]
To set the hilited row(s) of a dv, you set ```dvhilitedrows```, right?  That does not cause ```selectedRowChanged``` to fire, though.  Shouldn't it?

**Comment by trevordevore** [comment]
I don't think it should. Setting `the hilitedLines` of a field doesn't send the `selectionChanged` message. `dvHilitedRows` behaves in a similar way.
